### PR TITLE
[#94] Fixed: vanilla resteasy-jsonb application doesn't start

### LINKED ISSUE #94: Vanilla resteasy-jsonb application doesn't start
**Describe the bug**
Apprently this extension has hidden dependencies to jackson, which causes app to crash while booting up if only `quarkus-resteasy-jsonb` is present.

**To Reproduce**
```shell
mvn io.quarkus:quarkus-maven-plugin:1.13.2.Final:create \
    -DprojectGroupId=problem \
    -DprojectArtifactId=quarkus-resteasy-problem-playground \
    -DclassName="problem.HelloResource" \
    -Dpath="/hello" \
    -Dextensions="resteasy,resteasy-jsonb"
cd quarkus-resteasy-problem-playground
// add quarkus-resteasy-problem:0.9.5 to pom.xml
./mvnw clean quarkus:dev
```

App will not start properly, error stack trace in the logs:
```
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
```

**Expected behavior**
App should start without errors.

### PR DESCRIPTION
**Pull request by lwitkowski**
- Fixed detection for some internal jackson classes giving false-positive detections and failing at runtime when jsonb is used
- Removed jackson dependency in ProblemLogger for the price of slightly less pretty http-problem log (it uses `toString` instead of `ObjectMapper` to serialize parameters)
- Added `ArchUnit` constraints on postprocessors dependencies
- Added error message if json provider is not available
- Added workflow that checks minimal jackson and jsonb apps, [master is failing](https://github.com/TietoEVRY/quarkus-resteasy-problem/actions/runs/768462799) for jsonb quickstart, while [this branch is green](https://github.com/TietoEVRY/quarkus-resteasy-problem/actions/runs/768469729)

Closes #94

### CODE REVIEW

File: runtime/src/main/java/com/tietoevry/quarkus/resteasy/problem/postprocessing/ProblemLogger.java [hunk 1]
```diff
@@ -58,11 +55,11 @@ private String serialize(HttpProblem problem) {
     }
 
     private String serializeParameter(Map.Entry<String, Object> param) {
-        try {
-            return param.getKey() + "=" + mapper.writeValueAsString(param.getValue());
-        } catch (JsonProcessingException e) {
-            return param.getKey() + "=" + param.getValue().toString();
+        String serializedValue = param.getValue().toString();
```
Comment (pazkooda) [inline runtime/src/main/java/com/tietoevry/quarkus/resteasy/problem/postprocessing/ProblemLogger.java:58]: Not sure but from GitHub PullReq review perspective this smells NPE.

Comment (lwitkowski) [reply runtime/src/main/java/com/tietoevry/quarkus/resteasy/problem/postprocessing/ProblemLogger.java:58]: True that, will address.

File: deployment/pom.xml [hunk 2]
```diff
@@ -47,6 +47,11 @@
             <artifactId>quarkus-junit5</artifactId>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>io.quarkus</groupId>
+            <artifactId>quarkus-junit5-mockito</artifactId>
+            <scope>test</scope>
+        </dependency>
```
Comment (lwitkowski) [inline deployment/pom.xml:54]:
```suggestion
        asdasdasdasd
```

File: deployment/src/main/java/com/tietoevry/quarkus/resteasy/problem/deployment/ProblemProcessor.java [hunk 3]
```diff
@@ -27,72 +29,76 @@
...
+                new ResteasyJaxrsProviderBuildItem(EXTENSION_MAIN_PACKAGE + mapper.mapperClassName)));
     }
 
     @BuildStep(onlyIf = RestEasyReactiveDetector.class)
     void registerMappersForReactive(BuildProducer<ExceptionMapperBuildItem> providers) {
-        neededExceptionMappers().forEach(
-                (exceptionClass, mapperClass) -> providers.produce(
-                        new ExceptionMapperBuildItem(EXTENSION_MAIN_PACKAGE + mapperClass, exceptionClass,
-                                Priorities.AUTHENTICATION - 1, true)));
+        neededExceptionMappers().forEach(mapper -> providers.produce(
```
[the remark this answers is not in the document]
Comment (pazkooda) [reply deployment/src/main/java/com/tietoevry/quarkus/resteasy/problem/deployment/ProblemProcessor.java:102]: Just commit fully prefixed mappers instead of hidden "prefix" in method and this will be perfect code :)

**Review by pazkooda — APPROVED** [review]

File: deployment/src/main/java/com/tietoevry/quarkus/resteasy/problem/deployment/ProblemProcessor.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (lwitkowski) [reply deployment/src/main/java/com/tietoevry/quarkus/resteasy/problem/deployment/ProblemProcessor.java:112]: Done.
