### PR TITLE
[#343] Fix for: NullpointerException WebApplicationException when Response Headers not set

### LINKED ISSUE #343: NullpointerException WebApplicationException when Response Headers not set
When mapping a WebApplicationException whose response returns null for `getHeaders`, an NPE is thrown and the original exception informaiton is lost.

**To Reproduce**
- Quarkus version: `3.5.2`
- quarkus-resteasy-problem `3.1.0`

Use a rest client that returns null headers instead of an empty map (in my case, keycloak admin client).
```
    @Path("reproduce")
    @GET
    public RealmRepresentation reproduce() {
        return KeycloakBuilder.builder()
                .serverUrl("http://keycloak.obsidian.com")
                .clientId("admin-cli")
                .realm("404")
                .username("user")
                .password("password")
                .build()
                .realm("404")
                .toRepresentation();
    }
```
```
{
    "details": "Error id 44fbd7fa-b5c8-4c5e-87bf-91492cbd4d12-4, java.lang.NullPointerException: Cannot invoke \"jakarta.ws.rs.core.MultivaluedMap.forEach(java.util.function.BiConsumer)\" because the return value of \"jakarta.ws.rs.core.Response.getHeaders()\" is null",
    "stack": "java.lang.NullPointerException: Cannot invoke \"jakarta.ws.rs.core.MultivaluedMap.forEach(java.util.function.BiConsumer)\" because the return value of \"jakarta.ws.rs.core.Response.getHeaders()\" is null\n\tat com.tietoevry.quarkus.resteasy.problem.jaxrs.WebApplicationExceptionMapper.toProblem(WebApplicationExceptionMapper.java:28)\n\tat com.tietoevry.quarkus.resteasy.problem.jaxrs.WebApplicationExceptionMapper.toProblem(WebApplicationExceptionMapper.java:13)\n\tat com.tietoevry.quarkus.resteasy.problem.ExceptionMapperBase.toResponse(ExceptionMapperBase.java:23)\n\tat org.jboss.resteasy.reactive.server.core.RuntimeExceptionMapper.mapException(RuntimeExceptionMapper.java:100)\n\tat org.jboss.resteasy.reactive.server.core.ResteasyReactiveRequestContext.mapExceptionIfPresent(ResteasyReactiveRequestContext.java:337)\n\tat org.jboss.resteasy.reactive.server.handlers.ExceptionHandler.handle(ExceptionHandler.java:15)\n\tat io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)\n\tat io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)\n\tat org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)\n\tat org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)\n\tat org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)\n\tat org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:840)"
}
```

**Expected behavior**
Null headers should be handled gracefully:
```
{
    "status": 404,
    "title": "Not Found",
    "detail": "Received: 'Server response is: 404' when invoking: Rest Client method: 'org.keycloak.admin.client.token.TokenService#grantToken'",
    "instance": "/reproduce"
}
```

### PR DESCRIPTION
**Pull request by lwitkowski**
Fixes #343

### CODE REVIEW

File: runtime/src/main/java/com/tietoevry/quarkus/resteasy/problem/jaxrs/WebApplicationExceptionMapper.java [hunk 1]
```diff
@@ -22,10 +23,10 @@ protected HttpProblem toProblem(WebApplicationException exception) {
                 .withStatus(status)
                 .withDetail(exception.getMessage());
 
-        exception
-                .getResponse()
-                .getHeaders()
-                .forEach((header, values) -> values.forEach(value -> problem.withHeader(header, value)));
+        Optional.ofNullable(exception.getResponse().getHeaders())
+                .ifPresent(headers -> {
```
Comment (pazkooda) [inline runtime/src/main/java/com/tietoevry/quarkus/resteasy/problem/jaxrs/WebApplicationExceptionMapper.java:27]: `ifPresent` is [passe](https://dzone.com/articles/optional-ispresent-is-bad-for-you) (right from the design) 😉 

Prefer
```java
Optional.ofNullable(...).orElse(<empty>).forEach(h -> ...)
```

**Review by pazkooda — APPROVED** [review]
Small detail, but otherwise look good.

File: runtime/src/main/java/com/tietoevry/quarkus/resteasy/problem/jaxrs/WebApplicationExceptionMapper.java (hunk 1 above)
Comment (lwitkowski) [reply runtime/src/main/java/com/tietoevry/quarkus/resteasy/problem/jaxrs/WebApplicationExceptionMapper.java:27]: `ifPresent` != `isPresent` :P I see nothing wrong with `ifPresent`, it's much more readable (and obvious) than e.g `flatMap` for most developers, including me...
